FROM openjdk:14-alpine
ARG PROFILE
ARG SCHEMA_REGISTRY_USERNAME
ARG SCHEMA_REGISTRY_PASSWORD
ENV PROFILE $PROFILE
ENV SCHEMA_REGISTRY_USERNAME $SCHEMA_REGISTRY_USERNAME
ENV SCHEMA_REGISTRY_PASSWORD $SCHEMA_REGISTRY_PASSWORD
WORKDIR notification-service
COPY build/libs/notification-service.jar ./
CMD java -jar \
    -Dspring.profiles.active=$PROFILE \
    -DSCHEMA_REGISTRY_USERNAME=$SCHEMA_REGISTRY_USERNAME \
    -DSCHEMA_REGISTRY_PASSWORD=$SCHEMA_REGISTRY_PASSWORD \
    notification-service.jar