server:
  port: 6060
management:
  server:
    port: 6061
  endpoints:
    web:
      exposure:
        include: health, prometheus
spring:
  jmx:
    enabled: true
  kafka:
    bootstrap-servers: pc-mint:9092
    properties:
      schema.registry.url: http://pc-mint:9099
      specific.protobuf.value.type: com.pw.tms.TextMessageSentProto
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      group-id: ${GROUP_ID}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/oauth/.well-known/jwks.json
  data:
    mongodb:
      host: localhost
      port: 27017
      username: ns
      password: ns
      database: ns-db