spring:
  kafka:
    bootstrap-servers: kafka:29092
    properties:
      schema.registry.url: http://schema-registry:8081
      specific.protobuf.value.type: com.pw.tms.TextMessageSentProto
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      group-id: notification-service
  data:
    mongodb:
      host: mongo
      port: 27017
      username: ns
      password: ns
      database: ns-db