spring:
  kafka:
    bootstrap-servers: kafka-cluster-kafka-brokers.kafka:9092
    properties:
      schema.registry.url: http://schema-registry-svc.kafka:9099
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: ${SCHEMA_REGISTRY_USERNAME}:${SCHEMA_REGISTRY_PASSWORD}
      specific.protobuf.value.type: com.pw.tms.TextMessageSentProto
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      group-id: notification-service
  data:
    mongodb:
      host: mongodb-svc.mongo
      port: 27017
      username: ns
      password: ns
      database: ns-db